services:
  - type: web
    name: server
    env: node
    buildCommand: "cd server && npm install"
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
  - type: static
    name: client
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "client/dist"
